name: sign_up_phone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  get: 4.3.8
  intl_phone_number_input: ^0.7.0+2
  intl_phone_field: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
